### ISSUE TITLE
Time Management: Enrolled user limit? Times out.

### ISSUE THREAD

**Issue by jonathanpattison-sudo** [bdecentgmbh/moodle-local_learningtools#27]
Is there a limit on the number of enrolled users the Time Management plugin can handle? We used it on a course with more than 15000 enrolled users (not all active) and it times out. The course never loads.

**Comment by stefanscholz** [comment]
Hi @jonathanpattison-sudo , we've never tested it with a course of that size; do while we don't have a technical limit, I'm but surprised that it times out. For every user, and for every activity, dates need to be generated. That's a ton of data base request, both read and write.

In order to support such a large course, we'll probably need to implement something to handle the generation of dates asynchronously, rather than doing it all at once. 

Happy to add that to the improvements for the next release.

How many activities have you configured on your attempt?

**Comment by jonathanpattison-sudo** [comment]
None of the activities had had a date applied to them in the Time Management plugin. Also, when trying to uninstall the plugin page still lists the plugins but says they are missing from the disk. And we cannot access the course. It produces an error for existing and new users:

![image](https://github.com/user-attachments/assets/54cdf185-674d-4cbb-8e8c-6173b88911c9)

**Comment by stefanscholz** [comment]
Note for anybody that considers using Time Management: We're currently working on a complete re-write of Time Management. The new version will handle large courses well, but if you operate at scale, please test it before using it in production. If in doubt, ask us, we're happy to help.

Closing this issue because it will be fixed in the new version of Time Management.
