### ISSUE TITLE
update for Moodle 4.2-4.5?

### ISSUE THREAD

**Issue by Willtaylormd** [bdecentgmbh/moodle-local_learningtools#28]
Wondering what plans there might be to update the Learning Tools plugin (notes & bookmarks specifically) for Moole 4.2 - 4.5?  Finding this incredibly useful to my users, it's the only thing holding me back on version 4.1.

**Comment by stefanscholz** [comment]
Hi @Willtaylormd,

glad to hear that Learning Tools is useful for your users! 

I've personally used Learning Tools on several 4.2, 4.3 and 4.4 sites and for the most part, it works just fine. The only issues that I found were in the pro version (a link is broken to get to the manage dates report in 4.4+, and generating dates in Time Management throws an error on 4.4+).

We're working at the moment to implement official support for 4.5, so you won't have to wait much longer.

Feel free to test Learning Tools on one of our demo sites (e.g. bdecent.io, which is a 4.3 site) if you want.

Closing the issue because it will be fixed in the next release.

Cheers
Stefan
